version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: singlish_showdown
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./singlish-tea/Dockerfile
    env_file:
      - ./singlish-tea/.env
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: npm run dev
volumes:
  db_data:
