import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <nav className="w-full bg-white/20 backdrop-blur sticky top-0 z-50 shadow-sm">
          <div className="container mx-auto flex items-center gap-6 py-3 px-4">
            <Link href="/" className="font-bold text-lg hover:underline">Home</Link>
            <Link href="/leaderboard" className="hover:underline">Leaderboard</Link>
            <Link href="/content-management" className="hover:underline">Content Management</Link>
          </div>
        </nav>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
